# block 1
variables:
  VERSION: "1.0"
  NAME: "log-tthcc"
  PORT_LOCAL: "8091"
  PORT_PUBLIC: "8091"
  DOCKER_HUB: "neac/log-tthcc"
  DOCKER_USERNAME: deam2k
  DOCKER_PASSWORD: Docker1234
# end block 1

# block 2
before_script:
  - git --version
  - mvn -version
  - docker info
# end block 2

# block 3
stages:
  - setup
  - test
  - build
  - clear
  - deployment
# end block 3

# block 4
# Pull code ve
Setup EnviromentDesktop job: 
  stage: setup
  # services:
    # - docker:19.03.1-dind
  # image: docker:19.03.1
  script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    # - cd D:\annt\neac1\business-portal-api
    # - git clean
    - git pull origin sonnv
    - exit
  only:
    - sonnv
# end block 4

# block 5
test: 
  stage: test
  script:
    - mvn test -DtestServerType=local
    - exit
  only:
    - sonnv

# # Build fo
BuildAPP API job: 
  stage: build
  script:
    - docker build --no-cache -t "$NAME" .
    - exit
  only: 
    - sonnv
# end block 5

# block 6
# # # Clear fo
ClearAPP API job: 
  stage: clear
  script:
    # - rmdir "src"
    # - docker image prune --filter="dangling=true"
    - docker container stop "$NAME"
    - docker container rm "$NAME"
    - exit
  only: 
    - sonnv
# end block 6

# block 7
# #Run API
Deploy API job:
  stage: deployment
  script:
    - docker run -d -p $PORT_PUBLIC':'$PORT_LOCAL --name $NAME $NAME
    - docker tag $NAME $DOCKER_HUB':'$VERSION
    - docker push $DOCKER_HUB':'$VERSION
    - exit
  when: always
  only: 
    - sonnv
# end block 7
