#block 1
variables:
  VERSION: "1.0"
  NAME: "log-tthcc-ui"
  PORT_LOCAL: "80"
  PORT_PUBLIC: "8092"
  DOCKER_HUB: "neac/log-tthcc-ui"
  DOCKER_USERNAME: deam2k
  DOCKER_PASSWORD: Docker1234
#end block 1

#block 2
before_script:
  - git --version
  - docker info
#end block 2

#block 3
stages:
  - setup
  - test
  - build
  - clear
  - deployment
 #end block 3

#block 4
# Pull code ve
Setup EnviromentDesktop job: 
  stage: setup
  script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - git pull origin sonnv
    - exit
  only:
    - sonnv
 #end block 4

#block 5
test: 
  stage: test
  script:
#    - mvn test -DtestServerType=local
    - exit
  only:
    - sonnv
#end block 5

#block 6
# # Build fo
BuildAPP API job: 
  stage: build
  script:
    - docker build --no-cache -t "$NAME" .
    - exit
  only: 
    - sonnv
#end block 6

#block 7
# # # Clear fo
ClearAPP API job: 
  stage: clear
  script:
    - docker container stop "$NAME"
    - docker container rm "$NAME"
    - exit
  only: 
    - sonnv
#end block 7

#block 8
# #Run API
Deploy API job:
  stage: deployment
  script:
    - docker run -d -p $PORT_PUBLIC':'$PORT_LOCAL --name $NAME $NAME
    - docker tag $NAME $DOCKER_HUB':'$VERSION
    - docker push $DOCKER_HUB':'$VERSION
    - exit
  when: always
  only: 
    - sonnv
#end block 8
